### ISSUE TITLE
Gradle 8 support

### ISSUE THREAD

**Issue by Meemaw** [bufbuild/buf-gradle-plugin#177]
Would be great if this plugin supported Gradle version 8.

Seing task failing with:

```
Execution failed for task ':libs:protos:bufGenerate'.
> Extension with name 'buf' does not exist. Currently registered extension names: [ext]
```

**Comment by andrewparmet** [comment]
We use this plugin with Gradle 8 every day. This error looks different from what I'd expect if Gradle didn't support the plugin. Can you share a minimal reproducer?

**Comment by Meemaw** [comment]
Closing since there was something wonky going on, and things now work without issues.
